# Firstly, microk8s enable ingress
# And, annotations is just for Windows

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.kubernetes.io/use-regex: 'true'
spec:
  rules:
      - host: localservice.com
        http:
          paths:
            - path: /api/platform
              pathType: Prefix
              backend:
                service:
                  name: platform-clusterip-srv
                  port:
                    number: 80
            - path: /api/command/platform
              pathType: Prefix
              backend:
                service:
                  name: command-clusterip-srv
                  port:
                    number: 80