# After creating and applying this file, create secret key : microk8s.kubectl create secret generic mssql --from-literal=SA_PASSWORD=<password>

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
